name: locate
description: A Flutter plugin to fetch Location Data Feed on Android.
version: 1.2.0
author: Anjan Roy <anjanroy@yandex.com>
homepage: 'https://github.com/itzmeanjan/locate'

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.itzmeanjan.locate
        pluginClass: LocatePlugin
